// exports.BASEURL = "http://localhost:5000"
// exports.IMAGEURL = "http://localhost:5000/uploads"
exports.SOCKET_URL = "http://localhost:5000"
exports.IMAGEURL = "https://res-server-7eve.onrender.com/uploads"
exports.BASEURL ="https://res-server-7eve.onrender.com"